### ISSUE TITLE
TodoAdapter vs. TodoInteractor

### ISSUE THREAD

**Issue by przmv** [marconi/deferr#1]
It looks like the definitions of [`TodoAdapter` interface](https://github.com/marconi/deferr/blob/master/domains.go#L3-L8) and [`TodoInteractor` interface](https://github.com/marconi/deferr/blob/master/interfaces.go#L61-L66) are just the same. Why so? What's the purpose having two identical interfaces?

**Comment by marconi** [comment]
They don't have direct relationship, each layer's interface should be independent. It just so happen that in this case operations for adapter and web handlers are the same.

**Comment by przmv** [comment]
Thanks for the explanation!
